version: 2

models:
  - name: stg_local_bike__brands
    description: "This model contains the list of bikes' brands."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each bike's brand."
        tests:
            - unique
            - not_null

  - name: stg_local_bike__categories
    description: "This model contains the list of bikes' categories."
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each bike's category."
        tests:
            - unique
            - not_null
  
  - name: stg_local_bike__customers
    description: "This model contains information about customers."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null

  - name: stg_local_bike__order_items
    description: "This model contains details about each order, by item line, including product price, quantity, and discount rate."
    columns:
      - name: order_items_id
        description: "Primary key, unique identifier for each order-item: generated by concatenating order_id and item_id."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              name: order_id_id_foreign_key_in_stg_local_bike__order_items
              to: ref('stg_local_bike__orders')
              field: order_id
      - name: product_id
        description: "Foreign key linking the order item to the corresponding product."
        tests:
          - relationships:
              name: product_id_id_foreign_key_in_stg_local_bike__order_items
              to: ref('stg_local_bike__products')
              field: product_id
      - name: total_order_items_amount
        description: "The total amount for this order item, calculated as (quantity * list_price) * (1 - discount)."

  - name: stg_local_bike__orders
    description: "This model contains information about orders placed by customers."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: customer_id
        description: "Foreign key linking the order to the corresponding customer."
        tests:
          - relationships:
              name: customer_id_id_foreign_key_in_stg_local_bike__orders
              to: ref('stg_local_bike__customers')
              field: customer_id
      - name: store_id
        description: "Foreign key linking the order to the corresponding store."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_local_bike__orders
              to: ref('stg_local_bike__stores')
              field: store_id
      - name: staff_id
        description: "Foreign key linking the order to the corresponding staff member."
        tests:
          - relationships:
              name: staff_id_id_foreign_key_in_stg_local_bike__orders
              to: ref('stg_local_bike__staffs')
              field: staff_id

  - name: stg_local_bike__products
    description: "This model contains information about products."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "Foreign key linking the product to the corresponding brand."
        tests:
          - relationships:
              name: brand_id_id_foreign_key_in_stg_local_bike__products
              to: ref('stg_local_bike__brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the product to the corresponding category."
        tests:
          - relationships:
              name: category_id_id_foreign_key_in_stg_local_bike__products
              to: ref('stg_local_bike__categories')
              field: category_id

  - name: stg_local_bike__staffs
    description: "This model contains information about staff members."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff member."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the staff member to the corresponding store."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_local_bike__staffs
              to: ref('stg_local_bike__stores')
              field: store_id

  - name: stg_local_bike__stocks
    description: "This model contains information about products stock into stores."
    columns:
      - name: stock_id
        description: "Primary key, unique identifier for each combination of store and product: generated by concatenating store_id and product_id."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the stock info to the corresponding store."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_local_bike__stocks
              to: ref('stg_local_bike__stores')
              field: store_id
      - name: product_id
        description: "Foreign key linking the stock info to the corresponding product."
        tests:
          - relationships:
              name: product_id_id_foreign_key_in_stg_local_bike__stocks
              to: ref('stg_local_bike__products')
              field: product_id
  
  - name: stg_local_bike__stores
    description: "This model contains information about stores."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
            - unique
            - not_null